### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by RitaButusova** [RitaButusova/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by romaniki** [comment]
https://twitter.com/officalmrbean
https://www.facebook.com/MrBean
https://www.instagram.com/mrbean/
