### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by RitaButusova** [RitaButusova/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by romaniki** [comment]
Education

1975

Studied at Newcastle University and Oxford University and earned a master's degree in electrical engineering. 

Career

1979

Wrote for and starred in the BBC's Not the Nine O'clock News

1990

He starred as his originally developed character Mr. Bean on the television series of the same name. Mr. Bean was adapted for film in 1997 and enjoyed wide success.

Theatrical productions:

The Nerd (1984), 

The New Revue (1986) 

The Sneeze (1988). 

Television shows: 

Not the Nine O'Clock News (1979-1982), 

Blackadder (1983-1989)

The Thin Blue Line (1995-1996). 

Filmography:

1979–1982: Not the Nine O'Clock News

1983–1989: Blackadder

1983: Never Say Never Again

1988: The Appointments of Dennis Jennings

1989: The Tall Guy

1990–1995: Mr. Bean

1995–1996: The Thin Blue Line

1990: The Witches

1993: Hot Shots! Part Deux

1994: Four Weddings and a Funeral

1994: The Lion King

1997: Bean

2000: Maybe Baby

2001: Rat Race

2002: Scooby-Doo

2003: Johnny English

2003: Love Actually

2005: Keeping Mum

2007: Mr. Bean's Holiday

2011: Johnny English Reborn

2017: Huan Le Xi Ju Ren

2018: Johnny English Strikes Again

Awards

1980 and 1989

BBC TV Personality of the Year

1980

British Academy Award for best light entertainment television performance, British Academy of Film and Television Arts, for Not the Nine O'Clock News

1981

Laurence Olivier Award, best comedy performance of the year, Society of West End Theatre, for Rowan Atkinson in Revue

1989

British Academy Award for best light entertainment television performance, British Academy of Film and Television Arts, for Blackadder Goes Forth

1990

Golden Rose Award for Mr. Bean

1990

Montreaux Television Festival Award for Mr. Bean
