### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by RitaButusova** [RitaButusova/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by romaniki** [comment]
LANGUAGES
- 🇺🇸 ENGLISH

SKILLS
- incredibly capable behind the wheel
- juggle with one ball

CHARACTER

- philanthropist 
- humanitarian 
- egalitarian
- entrepreneurial
- progressive

LIKES 😃
[Trucking](https://www.youtube.com/watch?v=w9lmCpIzhFo), Aston Martins and Ferraris.

DISLIKES 😞
Pronouncing words that start with the letter B

WANTS 
Boost sales at the Mr Bean Shop
